name: Build EpiDoc Development Schema

on:
  push:
    branches: [ main ]
    paths:
      - 'sigidoc.odd'
  workflow-dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: teic/teidev-docker:latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
        with: 
          submodules: recursive
          fetch-depth: 0
      - name: "Checkout gh-pages branch"
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
      - name: "Checkout TEI stylesheets repo"
        uses: actions/checkout@v4
        with:
          repository: "TEIC/Stylesheets"
      - name: "Build Schema"
        run: |
          Stylesheets/bin/teitorng sigidoc.odd sigidoc.rng
          rm -rf gh-pages/schema/dev
          mkdir -p gh-pages/schema/dev
          cp schema/sigidoc.* gh-pages/schema/dev/
          tree -H '.' -T 'schema/' -I index.html -L 1 --noreport --charset utf-8 -o gh-pages/schema/index.html gh-pages/schema
          tree -H '.' -T 'dev/' -I index.html -L 1 --noreport --charset utf-8 -o gh-pages/schema/dev/index.html gh-pages/schema/dev
      - name: "Push to gh-pages branch"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: gh-pages
          branch: gh-pages
          commit_message: "Published development Schema."
