name: Build EpiDoc Development Schema

on:
  push:
    branches: [ main ]
    paths:
      - 'sigidoc.odd'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: teic/teidev-docker:latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Checkout gh-pages branch"
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
      - name: "Checkout TEI stylesheets repo"
        uses: actions/checkout@v4
        with:
          repository: "TEIC/Stylesheets"
          path: tei-stylesheets
      - name: "Build Schema"
        run: |
          tei-stylesheets/bin/teitorng sigidoc.odd sigidoc.rng
          rm -rf gh-pages/schema/dev
          mkdir -p gh-pages/schema/dev
          cp sigidoc.* gh-pages/schema/dev/
          tree -H '.' -T 'schema/' -I index.html -L 1 --noreport --charset utf-8 -o gh-pages/schema/index.html gh-pages/schema
          tree -H '.' -T 'dev/' -I index.html -L 1 --noreport --charset utf-8 -o gh-pages/schema/dev/index.html gh-pages/schema/dev
      - name: "Push to gh-pages branch."
        run: |
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Published development Schema."
          git push
