name: Update SigiDoc landing page from README

on:
  push:
    branches: [ main ]
    paths: 
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: "Checkout gh-pages branch"
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: "Publish README.md as index.html"
        uses: docker://pandoc/core:3.2
        with: 
          args: >-
            --standalone
            -f gfm
            -t html
            --shift-heading-level-by=-1
            --output=gh-pages/index.html
            README.md

      - name: "Push to gh-pages branch"
        run: |
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Published README."
          git push
